// Regenerates src/gvas/item-templates.ts: one game-authored struct_save
// element per item class, mined from real saves' world data. Donor-less adds
// in the editor clone these templates so they carry the class's correct item
// id and saved variables (see items.ts).
//
// Usage: bun run mine-templates [save.sav ...]
// With no args, mines every *.sav in %LOCALAPPDATA%/VotV/Saved/SaveGames.
// Pre-0.8 saves contribute nothing (their items carry no `names` id batch).

import { readdirSync } from "node:fs";
import { decodeStructBody, encodeStructBody, readGvas } from "../src/gvas/gvas";
import type { GvasFile } from "../src/gvas/gvas";
import { mineAuthoredElements } from "../src/gvas/items";

const OUT = `${import.meta.dir}/../src/gvas/item-templates.ts`;

// Dynamic per-instance names in the editor's own `key` style — never registry
// item ids (e.g. beehiveBranch elements carry keys, not ids).
const KEY_LIKE = /^[A-Za-z0-9_-]{22}$/;

function savePaths(): string[] {
  const args = process.argv.slice(2);
  if (args.length) return args;
  const dir = `${process.env.LOCALAPPDATA}/VotV/Saved/SaveGames`;
  return readdirSync(dir)
    .filter((f) => f.endsWith(".sav"))
    .map((f) => `${dir}/${f}`);
}

function versionOf(file: GvasFile): string {
  const v = file.root.find((p) => p.name.replace(/_\d+_[0-9A-Fa-f]{32}$/, "") === "Version")?.value;
  return v?.kind === "str" ? v.value : "unknown";
}

interface Candidate {
  id: string;
  bytes: Uint8Array;
}

const byClass = new Map<string, Map<string, Candidate[]>>(); // class -> idLower -> candidates
const sources: string[] = [];

for (const path of savePaths()) {
  const name = path.split(/[\\/]/).pop() ?? path;
  let file: GvasFile;
  try {
    file = readGvas(new Uint8Array(await Bun.file(path).arrayBuffer()));
  } catch (e) {
    console.error(`SKIP ${name}: ${e}`);
    continue;
  }
  const elements = mineAuthoredElements(file);
  let used = 0;
  for (const { classPath, id, el } of elements) {
    if (KEY_LIKE.test(id)) continue;
    used++;
    let ids = byClass.get(classPath);
    if (!ids) byClass.set(classPath, (ids = new Map()));
    const lower = id.toLowerCase();
    let cands = ids.get(lower);
    if (!cands) ids.set(lower, (cands = []));
    cands.push({ id, bytes: encodeStructBody(el) });
  }
  sources.push(`${name} (Version ${versionOf(file)}, ${used} elements)`);
  console.error(`OK   ${name}: ${used} usable elements`);
}

// A class qualifies only when every sighting agrees on one id (ids are FNames,
// so compare case-insensitively) — otherwise identity is ambiguous by class
// (junk props, food variants) and a donor in the save remains the only truth.
const included = new Map<string, Uint8Array>();
const excluded: string[] = [];
for (const [classPath, ids] of byClass) {
  if (ids.size > 1) {
    excluded.push(`${classPath} (${[...ids.keys()].slice(0, 4).join(", ")}${ids.size > 4 ? ", …" : ""})`);
    continue;
  }
  const cands = [...ids.values()][0]!;
  const best = cands.reduce((a, b) => (b.bytes.length < a.bytes.length ? b : a));
  const redecoded = encodeStructBody(decodeStructBody(best.bytes));
  if (Buffer.compare(Buffer.from(best.bytes), Buffer.from(redecoded)) !== 0) {
    throw new Error(`template for ${classPath} does not round-trip`);
  }
  included.set(classPath, best.bytes);
}

// One gzipped blob + offset index: the tagged property lists are so repetitive
// that whole-blob compression is ~24x, vs ~1.3 MiB as per-class base64.
const entries = [...included.entries()].sort(([a], [b]) => a.localeCompare(b));
let offset = 0;
const spans = entries.map(([cls, bytes]) => {
  const span = `  ${JSON.stringify(cls)}: [${offset}, ${bytes.length}],`;
  offset += bytes.length;
  return span;
});
const blob = Buffer.concat(entries.map(([, bytes]) => bytes));
const gz64 = Buffer.from(Bun.gzipSync(blob, { level: 9 })).toString("base64");
const header = `// GENERATED by scripts/mine-item-templates.ts — do not edit by hand.
// Regenerate: bun run mine-templates [save.sav ...]
//
// One game-authored struct_save element per item class, mined from world data
// (objectsData / non-player GObjStack) of real saves. The blob is the gzipped
// concatenation of the elements' GVAS property lists; the index maps
// classPath -> [offset, length] into the decompressed blob. Classes whose
// sightings disagree on the item id are excluded — for those, identity is
// ambiguous by class and only an in-save donor is trustworthy.
//
// Sources:
${sources.map((s) => `//   ${s}`).join("\n")}
// Classes: ${entries.length} (excluded ${excluded.length} ambiguous multi-id classes)
`;
await Bun.write(
  OUT,
  `${header}export const ITEM_TEMPLATES_GZ =\n  ${JSON.stringify(gz64)};\n\nexport const ITEM_TEMPLATE_INDEX: Record<string, readonly [number, number]> = {\n${spans.join("\n")}\n};\n`,
);

console.error(`\nwrote ${entries.length} templates to ${OUT}`);
console.error(`excluded multi-id classes (${excluded.length}):`);
for (const e of excluded) console.error(`  ${e}`);
console.error(`payload: ${(blob.length / 1024).toFixed(0)} KiB raw -> ${(gz64.length / 1024).toFixed(0)} KiB base64 gzip`);
